export const TOGGLE_VISIBLE = 'TOGGLE_VISIBLE';
export const TOGGLE_SHOW_SPACING = 'TOGGLE_SHOW_SPACING';
export const SET_SELECTED_NODE = 'SET_SELECTED_NODE';
export const SET_EDITING_NODE = 'SET_EDITING_NODE';