export const TOGGLE_VISIBLE = 'TOGGLE_VISIBLE';
export const TOGGLE_SELECTED_ELEMENTS = 'TOGGLE_SELECTED_ELEMENTS';
export const TOGGLE_SHOW_SPACING = 'TOGGLE_SHOW_SPACING';
export const SET_SELECTED_ELEMENTS = 'SET_SELECTED_ELEMENTS';