export const ADD_PAGE = 'ADD_PAGE';
export const UPDATE_OVERWRITES = 'UPDATE_OVERWRITES';
export const UPDATE_SELECTED_OVERWRITES = 'UPDATE_SELECTED_OVERWRITES';
export const CLEAR_SELECTED_OVERWRITES = 'CLEAR_SELECTED_OVERWRITES';
export const ALIAS_UPDATE_SELECTED_OVERWRITES = 'ALIAS_UPDATE_SELECTED_OVERWRITES';
export const ALIAS_UPDATE_OVERWRITES = 'ALIAS_UPDATE_OVERWRITES';
export const UPDATE_NODE = 'UPDATE_NODE';
export const POP_OVERWRITE = 'POP_OVERWRITE';